name: my-github-testing

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello Message
      run: echo "hello Word from Testig"
      
    
  my_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello Message
      run: echo "Hello word from Deploy Job"
